### ISSUE TITLE
Users should be able to generate a fresh daily task list from their pending tasks to mitigate task overload

### ISSUE THREAD

**Issue by kappanjoe** [kappanjoe/ccp7-solo-mvp.taskbud#15]
## Acceptance Criteria:

- [ ] User can refresh task list every day
- [ ] Remaining tasks are removed from main view
- [ ] Tasks with start date are persistent in daily list
- [ ] User is reminded of tasks with deadline but no start date to avoid task crunch
