### ISSUE TITLE
User should see task list immediately so they can manage tasks quickly

### ISSUE THREAD

**Issue by kappanjoe** [kappanjoe/ccp7-solo-mvp.taskbud#5]
## Acceptance Criteria:

- [x] User is greeted with task list upon opening app
- [x] User can view the following info for each task:
  - [x] What the task is
  - [x] If it is completed
  - [x] If it has a memo
  - [x] If it has a start date
  - [x] If it has a due date
